apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://obs-prometheus:9090
    isDefault: true

  - name: Tempo
    type: tempo
    access: proxy
    url: http://obs-tempo:3200

  - name: Loki
    type: loki
    access: proxy
    url: http://obs-loki:3100