apiVersion: apps/v1
kind: Deployment
metadata:
  name: msdelivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msdelivery
  template:
    metadata:
      labels:
        app: msdelivery
    spec:
      containers:
        - name: msdelivery
          image: seu_usuario/msdelivery:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "msdelivery_db"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              value: "garage_user"
            - name: RABBITMQ_PASSWORD
              value: "garage_password"
            - name: RABBITMQ_VHOST
              value: "/"
            - name: ORDER_EVENTS_EXCHANGE
              value: "order.events.exchange"
            - name: ORDER_NEW_QUEUE
              value: "order.new.v1.queue"
            - name: ORDER_NEW_ROUTING_KEY
              value: "order.new.v1"
            - name: ORDER_EVENTS_DLX
              value: "order.events.dlx"
            - name: ORDER_NEW_DLQ
              value: "order.new.v1.dlq"
            - name: ORDER_NEW_DLQ_ROUTING_KEY
              value: "order.new.v1.dlq"
            - name: RABBITMQ_PUBLISH_ENABLED
              value: "true"

