apiVersion: apps/v1
kind: Deployment
metadata:
  name: msorder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msorder
  template:
    metadata:
      labels:
        app: msorder
    spec:
      containers:
        - name: msorder
          image: seu_usuario/msorder:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "msorder_db"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
