# PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=user
quarkus.datasource.password=password
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/subscriptions

# Hibernate
quarkus.hibernate-orm.database.generation=none

# Kafka Outgoing
mp.messaging.outgoing.outbox-events.connector=smallrye-kafka
mp.messaging.outgoing.outbox-events.topic=outbox-events
mp.messaging.outgoing.outbox-events.value.serializer=io.cloudevents.kafka.CloudEventSerializer

# Swagger UI and OpenAPI
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui
quarkus.openapi.path=/openapi
quarkus.smallrye-openapi.info-title=User Service API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=API documentation for the User Service
quarkus.smallrye-openapi.info-contact-name=Your Name
quarkus.smallrye-openapi.info-contact-email=yourname@example.com
quarkus.smallrye-openapi.info-contact-url=https://example.com
