# Load topology (exchange/queues/bindings) at boot.
management.load_definitions = /etc/rabbitmq/definitions.json

# Keep default vhost and allow access via provided user/pass.
loopback_users.guest = false

