name: Build and Push WildFly SOA Image to ECR
on:
  push:
    paths:
      - "infraestructure/**"

jobs:
  build-image:
    runs-on: k8s-dsv
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Wildfly Image
        run: |
          cd infraestructure/images/wildfly-soa
          docker build -t wildfly-soa:latest .

  push-to-ecr:
    name: Push to Amazon ECR
    needs: build-image
    runs-on: k8s-dsv
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: us-east-1
      ECR_REPOSITORY: wildfly-soa
      REGISTRY_ALIAS: 260761541415.dkr.ecr.us-east-1.amazonaws.com

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-to-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Tag and Push Docker Image to ECR
        run: |
          IMAGE_TAG="public.ecr.aws/u1o3k2v3/wildfly-soa:latest"
          docker tag wildfly-soa:latest $IMAGE_TAG
          docker push $IMAGE_TAG
