name: Build and Push WildFly SOA Image to ECR
on:
  push:
    paths:
      - "infraestructure/**"

jobs:
  build-image:
    runs-on: k8s-dsv
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Wildfly Image
        run: |
          cd infraestructure/images/wildfly-soa
          docker build -t wildfly-soa:latest .

  push-to-docker-hub:
    name: Push to Docker Hub
    needs: build-image
    runs-on: k8s-dsv
    env:
      DOCKERHUB_REPO: gnuvinicius/eda-lab-soa
      DOCKERHUB_USERNAME: gnuvinicius
      DOCKERHUB_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    steps:
      - name: Configure Docker Hub Credentials
        run: |
          echo ${{ env.DOCKERHUB_TOKEN }} | docker login -u ${{ env.DOCKERHUB_USERNAME }} --password-stdin

      - name: Tag and Push Docker Image to Docker Hub
        run: |
          IMAGE_TAG="${{ env.DOCKERHUB_REPO }}:latest"
          docker tag wildfly-soa:latest $IMAGE_TAG
          docker push $IMAGE_TAG
