name: Build and Push WildFly SOA Image to ECR
on:
  push:
    paths:
      - "infraestructure/**"

jobs:
  build-image:
    runs-on: k8s-dsv
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Wildfly Image
        run: |
          cd infraestructure/images/wildfly-soa
          docker build -t wildfly-soa:latest .

  # JOB 3: Push para o Docker Hub
  docker-push:
    needs: docker-build
    runs-on: k8s-dsv
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Public ECR
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Tag and Push to Public ECR
        run: |
          IMAGE_TAG="public.ecr.aws/u1o3k2v3/wildfly-soa:latest"

          docker tag wildfly-soa:latest $IMAGE_TAG
          docker push $IMAGE_TAG
